### ISSUE TITLE
Edit Profile : Upload image header

### ISSUE THREAD

**Issue by anhsbolic** [teamcookiesstudio/kamikerjaremote-laravel#18]

**Comment by anhsbolic** [comment]
- Ada penjelasan ukuran dimensi saat upload (nanti sy request layout ny)
- validasi ukuran image dimention di laravelny ya

ukuran header image
width : 1000 px
height : 200 px

**Comment by anhsbolic** [comment]
image nya di set k HTML kang @hafizu97

**Comment by Aslam97** [comment]
Oke siap kang @anhsbolic
