### ISSUE TITLE
Profile Page : layout for skill set

### ISSUE THREAD

**Issue by anhsbolic** [teamcookiesstudio/kamikerjaremote-laravel#37]
ini skill set nya cm satu row, jadi memanjang. Mohon dibuat ke bawah ketika satu baris udh penuh

![image](https://user-images.githubusercontent.com/30040146/38788095-20615b28-415c-11e8-8b7f-09a7807bc76e.png)

**Comment by ndhik** [comment]
<img width="725" alt="screen shot 2018-04-17 at 08 33 15" src="https://user-images.githubusercontent.com/1467768/38843609-0a8a1f7e-421a-11e8-86b5-3773ea028528.png">

just import the latest css
